import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { cartAction } from "../Redux/Reducers/cart";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { value } = useSelector((state) => state.persistedReducer.cart);
  const diapatch = useDispatch();
  return (
    <>
      <Head>
        <title>Redux-toolkit-presist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="m-auto">
          <div>The value of the cart is {value}</div>
          <button onClick={() => diapatch(cartAction.change())}>Change</button>
        </div>
      </div>
    </>
  );
}
